# Generated by Django 4.1.1 on 2022-09-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_productgeneralcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgeneralcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
