# Generated by Django 4.1.1 on 2022-09-15 23:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_product_srp_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='srp_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
