# Generated by Django 4.1.1 on 2022-09-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_shipment_gross_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
