# Generated by Django 4.1.1 on 2022-12-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facmasys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionservice',
            name='extension_head',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ref_extension_head', to=settings.AUTH_USER_MODEL),
        ),
    ]
