# Generated by Django 4.1.1 on 2022-12-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facmasys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extensionservice',
            old_name='extension_head',
            new_name='extension_head_id',
        ),
    ]
