# Generated by Django 4.1.1 on 2022-12-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facmasys', '0003_rename_extension_head_id_extensionservice_extension_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_published',
            name='abstract',
        ),
    ]
