# Generated by Django 4.1.1 on 2022-12-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facmasys', '0004_remove_research_published_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_track', models.CharField(blank=True, choices=[('Web and Mobile Development', 'Web and Mobile Development'), ('Service Management Program', 'Service Management Program'), ('Business Analytics', 'Business Analytics'), ('None', 'None')], default='None', max_length=50, null=True)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
