# Generated by Django 4.1.1 on 2022-12-30 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facmasys', '0005_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
