# Generated by Django 4.1.1 on 2022-12-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_presented',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='research_published',
            name='faculty_id',
        ),
    ]
