# Generated by Django 4.1.1 on 2022-12-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0002_remove_research_presented_faculty_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_presented',
            name='presented_id',
        ),
        migrations.RemoveField(
            model_name='research_published',
            name='published_id',
        ),
    ]
