# Generated by Django 4.1.1 on 2022-12-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0003_extensionservice_faculty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='presented_id',
        ),
        migrations.RemoveField(
            model_name='research',
            name='published_id',
        ),
        migrations.AddField(
            model_name='research_presented',
            name='published_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_member.research'),
        ),
        migrations.AddField(
            model_name='research_published',
            name='presented_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_member.research'),
        ),
    ]
