# Generated by Django 4.1.1 on 2022-12-29 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_icon.png', upload_to='Profile_Images')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user_role', models.CharField(choices=[('faculty', 'Faculty'), ('depthead', 'Department Head'), ('researchcoor', 'Research Coordinator'), ('extensioncoor', 'Extension Coordinator')], default='faculty', max_length=30)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
