# Generated by Django 4.1.1 on 2022-12-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facmasys', '0006_departments_date_added'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handled_subjects',
            field=models.ManyToManyField(to='facmasys.subjects'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spec_track',
            field=models.CharField(choices=[('Web and Mobile Development', 'Web and Mobile Development'), ('Service Management Program', 'Service Management Program'), ('Business Analytics', 'Business Analytics'), ('None', 'None')], default='None', max_length=50, null=True),
        ),
    ]
