# Generated by Django 4.1.1 on 2022-12-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='user',
        ),
    ]
