# Generated by Django 4.1.1 on 2022-09-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_order_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='general_category.jpg', upload_to='General_Category_Images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecificCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='specific_category.jpg', upload_to='Specific_Category_Images')),
                ('general_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productgeneralcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productspecificcategory'),
        ),
    ]
