# Generated by Django 4.1.1 on 2022-09-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_car_productbrand_product_brand_product_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
