# Generated by Django 4.1.1 on 2022-09-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='Product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_qty_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='part_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sellable_online',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='srp_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
