# Generated by Django 4.1.1 on 2022-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(blank=True, to='dashboard.car'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_qty_limit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
