# Generated by Django 4.1.1 on 2022-09-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_product_srp_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellable_online',
            field=models.BooleanField(default=False),
        ),
    ]
