# Generated by Django 4.1.1 on 2022-12-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty_member', '0003_remove_research_presented_presented_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_presented',
            name='faculty_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='research_presented',
            name='presented_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_member.research'),
        ),
        migrations.AddField(
            model_name='research_published',
            name='faculty_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='research_published',
            name='published_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_member.research'),
        ),
    ]
