# Generated by Django 4.1.1 on 2022-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
