# Generated by Django 4.1.1 on 2022-10-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productimage_delete_prod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
