# Generated by Django 4.1.1 on 2022-10-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_supplierarchive_shipmentarchive_servicearchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentarchive',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
