# Generated by Django 4.1.1 on 2022-10-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_service_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
    ]
