# Generated by Django 4.1.1 on 2022-11-26 18:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_delete_product_delete_productattribute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='shipment',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
