# Generated by Django 4.1.1 on 2022-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicearchive',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
