# Generated by Django 4.1.1 on 2022-11-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_car_cararchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
