# Generated by Django 4.1.1 on 2022-11-27 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_shipment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
