# Generated by Django 4.1.1 on 2022-09-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_shipment_gross_amount_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services.jpg', null=True, upload_to='Services_Images'),
        ),
    ]
