# Generated by Django 4.1.1 on 2022-10-15 21:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_productimage_alter_shipment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
