# Generated by Django 4.1.1 on 2022-10-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_shipmentarchive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services.png', null=True, upload_to='ServicesImages'),
        ),
    ]
