# Generated by Django 4.1.1 on 2022-11-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_shipmentarchive_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services.png', null=True, upload_to='Service_Images'),
        ),
    ]
