# Generated by Django 4.1.1 on 2022-11-29 14:06

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_shipment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': (django.db.models.functions.text.Lower('make'), django.db.models.functions.text.Lower('model'), django.db.models.functions.text.Lower('sub_model'), '-year')},
        ),
        migrations.AlterModelOptions(
            name='cararchive',
            options={'ordering': (django.db.models.functions.text.Lower('make'), django.db.models.functions.text.Lower('model'), django.db.models.functions.text.Lower('sub_model'), '-year')},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
        migrations.AlterModelOptions(
            name='servicearchive',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='shipmentarchive',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
        migrations.AlterModelOptions(
            name='supplierarchive',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
    ]
