# Generated by Django 4.1.1 on 2022-09-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Category1', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productspecificcategory'),
        ),
    ]
