# Generated by Django 4.1.1 on 2022-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgeneralcategory',
            options={'verbose_name_plural': 'General Categories'},
        ),
        migrations.AlterModelOptions(
            name='productspecificcategory',
            options={'verbose_name_plural': 'Specific Categories'},
        ),
        migrations.AlterField(
            model_name='productspecificcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
