# Generated by Django 4.1.1 on 2022-09-19 01:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_supplier_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
