# Generated by Django 4.1.1 on 2022-09-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_shipment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
