# Generated by Django 4.1.1 on 2022-09-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_servicecategory_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productspecificcategory',
            name='general_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='ProductGeneralCategory',
        ),
        migrations.DeleteModel(
            name='ProductSpecificCategory',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
