# Generated by Django 4.1.1 on 2022-12-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_settings_day_settings_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=150, null=True, unique=True)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
