# Generated by Django 4.1.1 on 2022-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_storeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.BooleanField(default=False, null=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=20)),
                ('time', models.TimeField(null=True)),
                ('day', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
