# Generated by Django 4.1.1 on 2022-12-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_emailnotification_delete_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.DeleteModel(
            name='StoreInfo',
        ),
    ]
