# Generated by Django 4.1.1 on 2022-12-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_delete_emailnotification_delete_storeinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
