# Generated by Django 4.1.1 on 2022-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_staff_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('depthead', 'Department Head'), ('researchcoor', 'Research Coordinator'), ('extensioncoor', 'Extension Coordinator')], default='faculty', max_length=30),
        ),
    ]
