# Generated by Django 4.1.1 on 2022-12-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='user_type',
            field=models.CharField(choices=[('Deparment Head', 'Deparment Head'), ('Research Coordinator', 'Research Coordinator'), ('Extension Coordinator', 'Extension Coordinator')], default='Deparment Head', max_length=100),
        ),
        migrations.CreateModel(
            name='Announcements_ResearchCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(max_length=200)),
                ('deadline_start', models.DateField()),
                ('deadline_end', models.DateField()),
                ('agenda', models.CharField(choices=[('On Call Papers', 'On Call Papers'), ('Journal Publication', 'Journal Publication'), ('Special Issues', 'Special Issues'), ('Intellectual Property Rights', 'Intellectual Property Rights'), ('Preparation of Instructional Materials', 'Preparation of Instructional Materials'), ('Revision of Research Guidelines', 'Revision of Research Guidelines'), ('Acknowledgement of Research Guidelines', 'Acknowledgement of Research Guidelines'), ('Research and Innovation', 'Research and Innovation'), ('Others', 'Others')], default='On Call Papers', max_length=100)),
                ('reference_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.announcements')),
            ],
        ),
        migrations.CreateModel(
            name='Announcements_ExtensionCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(max_length=200)),
                ('extension_address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('agenda', models.CharField(choices=[('On Call Papers', 'On Call Papers'), ('Signing of MOA', 'Signing of MOA'), ('Discussion of MOA', 'Discussion of MOA'), ('Partnership Programs', 'Partnership Programs'), ('Development Programs', 'Development Programs'), ('Extension Projects', 'Extension Projects'), ('Camp Projects', 'Camp Projects'), ('College Accreditation', 'College Accreditation'), ('Others', 'Others')], default='On Call Papers', max_length=100)),
                ('reference_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.announcements')),
            ],
        ),
        migrations.CreateModel(
            name='Announcements_DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(max_length=200)),
                ('agenda', models.CharField(choices=[('Urgent', 'Urgent'), ('Just In', 'Just In'), ('Important', 'Important'), ('Emergency', 'Emergency'), ('Acknowledgements', 'Acknowledgements'), ('FYI', 'FYI'), ('Event', 'Event'), ('News', 'News'), ('Greetings', 'Greetings'), ('Others', 'Others')], default='Greetings', max_length=100)),
                ('reference_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.announcements')),
            ],
        ),
    ]
