# Generated by Django 4.1.1 on 2022-12-29 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_announcements_user_type_announcements_researchcoord_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Feeds',
        ),
        migrations.RenameModel(
            old_name='Announcements_DepartmentHead',
            new_name='Feeds_DepartmentHead',
        ),
        migrations.RenameModel(
            old_name='Announcements_ExtensionCoord',
            new_name='Feeds_ExtensionCoord',
        ),
        migrations.RenameModel(
            old_name='Announcements_ResearchCoord',
            new_name='Feeds_ResearchCoord',
        ),
    ]
