# Generated by Django 4.1.1 on 2022-12-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_announcements_feeds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds_departmenthead',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='feeds_extensioncoord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feeds_extensioncoord',
            name='extension_address',
        ),
        migrations.RemoveField(
            model_name='feeds_extensioncoord',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='feeds_researchcoord',
            name='issued_by',
        ),
    ]
