# Generated by Django 4.1.1 on 2022-10-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_remove_cartproduct_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='car',
            new_name='car_make',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='contact',
        ),
    ]
