# Generated by Django 4.1.1 on 2022-10-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_order_subtotal_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
