# Generated by Django 4.1.1 on 2022-10-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_order_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_quantity',
        ),
    ]
