# Generated by Django 4.1.1 on 2022-10-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_order_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
