# Generated by Django 4.1.1 on 2022-10-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_cartproduct_product_alter_orderproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product',
            new_name='product_title',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='item_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
