# Generated by Django 4.1.1 on 2022-10-16 06:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_product_cartproduct_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
