# Generated by Django 4.1.1 on 2022-10-16 09:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_cartproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='product_title',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='item_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
