# Generated by Django 4.1.1 on 2022-10-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_rename_product_orderproduct_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(max_length=20),
        ),
    ]
