# Generated by Django 4.1.1 on 2022-10-16 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_order_subtotal_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(639999999999)]),
        ),
    ]
