# Generated by Django 4.1.1 on 2022-10-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
