# Generated by Django 4.1.1 on 2022-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_customer_address_alter_customer_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
