# Generated by Django 4.1.1 on 2022-10-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Completed', max_length=20, null=True),
        ),
    ]
