# Generated by Django 4.1.1 on 2022-10-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_rename_date_order_date_created_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
