# Generated by Django 4.1.1 on 2022-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
