# Generated by Django 4.1.1 on 2022-10-20 08:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_orderproduct_date_orderservice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
