# Generated by Django 4.1.1 on 2022-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_alter_order_date_created_alter_orderproduct_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_status',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('GCASH', 'GCASH'), ('PAYMAYA', 'PAYMAYA'), ('COINS.PH', 'COINS.PH')], default='Cash', max_length=20),
        ),
    ]
