# Generated by Django 4.1.1 on 2022-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_alter_order_options_alter_customer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
