# Generated by Django 4.1.1 on 2022-11-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_order_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plate_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
