# Generated by Django 4.1.1 on 2022-11-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customer'),
        ('sales', '0038_alter_orderproduct_cost_alter_orderproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
