# Generated by Django 4.1.1 on 2022-12-01 04:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_car_options_alter_cararchive_options_and_more'),
        ('sales', '0039_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.CharField(max_length=100, null=True)),
                ('product_title', models.CharField(max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost', models.DecimalField(decimal_places=2, default=1, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='OrderServiceArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('labor', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service')),
            ],
        ),
    ]
