# Generated by Django 4.1.1 on 2022-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_orderproductarchive_orderservicearchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Credit/Debit', 'Credit/Debit')], default='Cash', max_length=20),
        ),
    ]
